### ISSUE TITLE
Ucars Problem

### ISSUE THREAD

**Issue by blakedj012** [Jakllp/ucars#1]
Da man für Ucars keine Fehler eintragen kann und ich gesehen habe das Du aus Deutschland kommst schreibe ich mal in Deutsch. ^^

Also Danke erstmal das du diese beiden Plugins für die neueren Versionen kompatibel gemacht hast.  Aber es gibt noch ein paar Probleme siehe dem Fehler bei Mariokart und auch mit Ucars habe ich welche. Zb kann man keine Slaps richtig hochfahren. Manchmal funktioniert es manchmal nicht da bleibt man dann einfach hängen. 

Auch functioniert /reloaducars nicht. Also wenn ich Änderungen an der config mache und diese dann den Befehl eingebe kommt zwar das die Configs neu geladen wurden aber die Änderungen wurden nicht übernommen. 

Hast Du vielleicht ein Discord oder sowas? 

LG BLaKe

**Comment by Jakllp** [comment]
Fixed in latest version
