### ISSUE TITLE
1.21.2-Support

### ISSUE THREAD

**Issue by SOM-0x3B1** [Jakllp/ucars#8]
The minecart only accelerates for a split second after a key is pressed or released.
Holding down 'W' has no effect on the car, unless we spam press it or hold it down while spamming other functional keys (e.g. 'A', 'D', 'E' or 'T').

The problem started with version 1.21.2 and is still present in 1.21.3.

(Also thank you so much for maintaining this plugin, our entire project server depends on it <3)

**Comment by Jakllp** [comment]
When the hell did those MC-Versions release xD  
I'll look into it soon

**Comment by Jakllp** [comment]
Issue found, fix incoming  
It's Minecraft-Version-Matching and Reflection

**Comment by Jakllp** [comment]
Alright...  
1.21.1 was easy to get going but there seems to have been a bigger change to packets in 1.21.2.  
UCars uses Protocollib to interact with packets and it seems like Protocollib does not properly handle those packet-changes (yet)  
Right now without annoying rewrites/writing mojang-mapping-modules it won't be possible to update.

BUT:  
Protocollib for 1.21.2/3 is still in early stages so I'll just wait a bit longer. I'm guessing that Protocollib will adjust to the packet-changes and there won't be any rewrites necessary on our side.

**Comment by Jakllp** [comment]
Turns out they completely changed the movement-code in 1.21.2+.  

I have no clue how your cars moved in the first place as packets were broken as well and you should have never gotten *anywhere* lol.  
But I am now at that point as well: I get it to move but only for a tiny bit. Will have to write a new type of movement-system/a wrapper for it.

**Comment by Jakllp** [comment]
Fixed with [1.21-R1.1.5](https://github.com/Jakllp/ucars/releases/tag/1.21-R1.1.5)
